FaceRecoApp/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
app_name='FaceRecoProj'
urlpatterns=[
    path('',views.home,name= 'home'),
    path('FaceRecoApp/',views.face_recognizer,name='FaceRecoApp'),
    path('FaceRecoApp/modules',views.class_modules,name='class_modules'),
    path('student_info/<int:student_id>',views.student_info,name='student_info'),
    path('result_submission/',views.result_submission,name='result_submission'),
    path('FaceRecoApp/updateStatus',views.updateStatus,name='updateStatus'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
]

FaceRecoProj/urls.py
from django.contrib import admin
from django.urls import include, path,re_path 
from . import views

urlpatterns = [
    path('thankyou/',views.thankyou , name= 'thankyou'),
    path("admin/", admin.site.urls),
    path('',include('FaceRecoApp.urls'),name='FaceRecoApp'),
]

FaceRecoProj/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpRequest,HttpResponsePermanentRedirect,HttpResponseNotFound,HttpResponseRedirect


def thankyou(request):
    return render(request ,'thankyou.html')

FaceRecoProj/templates/thankyou.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style>
      h1,
      h2,
      p {
        margin: auto;
        display: block;
        padding: 50px;
        font-size: 24px;
        font-weight: 700;
        text-align: center;
      }
    </style>
  </head>
  <body>
    <h1>From the name of our company :</h1>
    <h2>we want to thank you for your submission us.</h2>
    click here to return to the main page
    <a href="{% url 'FaceRecoProj:home'%}">click here</a>
  </body>
</html>