FaceRecoApp/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
app_name='FaceRecoProj'
urlpatterns=[
    path('',views.home,name= 'home'),
    path('FaceRecoApp/',views.face_recognizer,name='FaceRecoApp'),
    path('FaceRecoApp/modules',views.class_modules,name='class_modules'),
    path('student_info/<int:student_id>',views.student_info,name='student_info'),
    path('result_submission/',views.result_submission,name='result_submission'),
    path('FaceRecoApp/updateStatus',views.updateStatus,name='updateStatus'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
]

FaceRecoProj/urls.py
from django.contrib import admin
from django.urls import include, path,re_path 
from . import views

urlpatterns = [
    path('thankyou/',views.thankyou , name= 'thankyou'),
    path("admin/", admin.site.urls),
    path('',include('FaceRecoApp.urls'),name='FaceRecoApp'),
]

FrontEnd/templates/UtilityTemplates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/build.css' %}" />
  </head>
  <body>
    <div class="mx-auto w-3/5 pt-10">
      {% include 'UtilityTemplates/header.html' %} {% block content %}
      {%endblock%} {% include 'UtilityTemplates/footer.html' %}
    </div>
    <script src="{% static 'js/flowbite.min.js' %}"></script>
  </body>
</html>

FrontEnd/templates/UtilityTemplates/footer.html
{% load static %}

<footer class="bg-white dark:bg-gray-900">
  <div class="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
    <div class="md:flex md:justify-between">
      <div class="mb-6 md:mb-0">
        <a href="#" class="flex items-center">
          <img
            src="{% static 'img/MainLogo.jpg' %}"
            class="me-3 h-8"
            alt="FaceReco Logo"
          />
          <span
            class="self-center whitespace-nowrap text-2xl font-semibold dark:text-white"
            >FaceRecognizer</span
          >
        </a>
      </div>
      <div class="grid grid-cols-2 gap-8 sm:grid-cols-3 sm:gap-6">
        <div>
          <h2
            class="mb-6 text-sm font-semibold uppercase text-gray-900 dark:text-white"
          >
            Resources
          </h2>
          <ul class="font-medium text-gray-500 dark:text-gray-400">
            <li>
              <a href="" class="hover:underline">About Us</a>
            </li>
          </ul>
        </div>
        <div>
          <h2
            class="mb-6 text-sm font-semibold uppercase text-gray-900 dark:text-white"
          >
            Follow us
          </h2>
          <ul class="font-medium text-gray-500 dark:text-gray-400">
            <li class="mb-4">
              <a href="" class="hover:underline">Github</a>
            </li>
            <li>
              <a href="https://discord.gg/4eeurUVvTy" class="hover:underline"
                >Discord</a
              >
            </li>
          </ul>
        </div>
        <div>
          <h2
            class="mb-6 text-sm font-semibold uppercase text-gray-900 dark:text-white"
          >
            Legal
          </h2>
          <ul class="font-medium text-gray-500 dark:text-gray-400">
            <li class="mb-4">
              <a href="#" class="hover:underline">Privacy Policy</a>
            </li>
            <li>
              <a href="#" class="hover:underline">Terms &amp; Conditions</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <hr class="my-6 border-gray-200 dark:border-gray-700 sm:mx-auto lg:my-8" />
    <div class="sm:flex sm:items-center sm:justify-between">
      <span class="text-sm text-gray-500 dark:text-gray-400 sm:text-center"
        >© 2023
        <a href="https://flowbite.com/" class="hover:underline">Flowbite™</a>.
        All Rights Reserved.
      </span>
    </div>
  </div>
</footer>

FrontEnd/templates/UtilityTemplates/header.html
{% load static %}

<header>
  <nav class="border-gray-200 bg-white px-4 py-2.5 dark:bg-gray-800 lg:px-6">
    <div
      class="mx-auto flex max-w-screen-xl flex-wrap items-center justify-between"
    >
      <a href="https://flowbite.com" class="flex items-center">
        <img
          src="{% static 'img/MainLogo.jpg' %}"
          class="mr-3 h-6 sm:h-9"
          alt="FaceReco Logo"
        />
        <span
          class="self-center whitespace-nowrap text-xl font-semibold dark:text-white"
          >FaceRecognizer</span
        >
      </a>
      <div class="flex items-center lg:order-2">
        <a
          href="{% url 'FaceRecoProj:login' %}"
          class="mr-2 rounded-lg px-4 py-2 text-sm font-medium text-gray-800 hover:bg-gray-50 focus:outline-none focus:ring-4 focus:ring-gray-300 dark:text-white dark:hover:bg-gray-700 dark:focus:ring-gray-800 lg:px-5 lg:py-2.5"
          >Log in</a
        >
        <a
          href="{% url 'FaceRecoProj:signup' %}"
          class="mr-2 rounded-lg bg-green-500 px-4 py-2 text-sm font-medium text-white hover:bg-green-800 focus:outline-none focus:ring-4 focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800 lg:px-5 lg:py-2.5"
          >Get started</a
        >
        <button
          data-collapse-toggle="mobile-menu-2"
          type="button"
          class="ml-1 inline-flex items-center rounded-lg p-2 text-sm text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600 lg:hidden"
          aria-controls="mobile-menu-2"
          aria-expanded="false"
        >
          <span class="sr-only">Open main menu</span>
          <svg
            class="h-6 w-6"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill-rule="evenodd"
              d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
              clip-rule="evenodd"
            ></path>
          </svg>
          <svg
            class="hidden h-6 w-6"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill-rule="evenodd"
              d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
              clip-rule="evenodd"
            ></path>
          </svg>
        </button>
      </div>
      <div
        class="hidden w-full items-center justify-between lg:order-1 lg:flex lg:w-auto"
        id="mobile-menu-2"
      >
        <ul
          class="mt-4 flex flex-col font-medium lg:mt-0 lg:flex-row lg:space-x-8"
        >
          <li>
            <a
              href="#"
              class="block rounded bg-green-500 py-2 pl-3 pr-4 text-white dark:text-white lg:bg-transparent lg:p-0 lg:text-green-500"
              aria-current="page"
              >Home</a
            >
          </li>
          <li>
            <a
              href="#"
              class="block border-b border-gray-100 py-2 pl-3 pr-4 text-gray-700 hover:bg-gray-50 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white lg:border-0 lg:p-0 lg:hover:bg-transparent lg:hover:text-primary-700 lg:dark:hover:bg-transparent lg:dark:hover:text-white"
              >Company</a
            >
          </li>
          <li>
            <a
              href="#"
              class="block border-b border-gray-100 py-2 pl-3 pr-4 text-gray-700 hover:bg-gray-50 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white lg:border-0 lg:p-0 lg:hover:bg-transparent lg:hover:text-primary-700 lg:dark:hover:bg-transparent lg:dark:hover:text-white"
              >Marketplace</a
            >
          </li>
          <li>
            <a
              href="#"
              class="block border-b border-gray-100 py-2 pl-3 pr-4 text-gray-700 hover:bg-gray-50 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white lg:border-0 lg:p-0 lg:hover:bg-transparent lg:hover:text-primary-700 lg:dark:hover:bg-transparent lg:dark:hover:text-white"
              >Features</a
            >
          </li>
          <li>
            <a
              href="#"
              class="block border-b border-gray-100 py-2 pl-3 pr-4 text-gray-700 hover:bg-gray-50 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white lg:border-0 lg:p-0 lg:hover:bg-transparent lg:hover:text-primary-700 lg:dark:hover:bg-transparent lg:dark:hover:text-white"
              >Team</a
            >
          </li>
          <li>
            <a
              href="#"
              class="block border-b border-gray-100 py-2 pl-3 pr-4 text-gray-700 hover:bg-gray-50 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white lg:border-0 lg:p-0 lg:hover:bg-transparent lg:hover:text-primary-700 lg:dark:hover:bg-transparent lg:dark:hover:text-white"
              >Contact</a
            >
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>